spring:
                                         redis:
                                           host: 192.168.5.101
                                           port: 6380
                                           test1: 'classpath:/redis/test1.lua'